# ------------------------------------------------------------------------------
# Copyright 2018 Frank V. Castellucci and Arthur Greef
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ------------------------------------------------------------------------------

version: '2.1'

services:

   units-processor:
     image: hashblock/hashblock-units-tp:latest
     container_name: hashblock-units-tp
     depends_on:
       - validator
     command: "bash -c \"\
         sleep 1 &&
         units-tp -vv \
           -C tcp://validator:4004 \
       \""
     stop_signal: SIGKILL

   resource-processor:
     image: hashblock/hashblock-resource-tp:latest
     container_name: hashblock-resource-tp
     depends_on:
       - units-processor
     command: "bash -c \"\
         sleep 1 &&
         resource-tp -vv \
           -C tcp://validator:4004 \
       \""
     stop_signal: SIGKILL

  match-processor:
    image: hashblock/hashblock-match-tp:latest
    container_name: hashblock-match-tp
    depends_on:
      - resource-processor
    command: "bash -c \"\
        sleep 1 &&
        match-tp -vv \
          -C tcp://validator:4004 \
      \""
    stop_signal: SIGKILL

  settings-tp:
    image: hyperledger/sawtooth-settings-tp:latest
    container_name: sawtooth-settings-tp-local
    depends_on:
      - validator
    entrypoint: settings-tp -vv -C tcp://validator:4004
    stop_signal: SIGKILL

  validator:
    image: hyperledger/sawtooth-validator:latest
    container_name: sawtooth-validator-local
    expose:
      - 4004
      - 8800
    ports:
      - "4004:4004"
      - "8800:8800"
    entrypoint: "bash -c \"\
        sawtooth-validator -vv \
          --endpoint tcp://__DNS__NODEINDEX__.westus2.cloudapp.azure.com:8800 \
          --peers tcp://__DNS__PEERINDEX0__.westus2.cloudapp.azure.com:8800,tcp://__DNS__PEERINDEX1__.westus2.cloudapp.azure.com:8800,tcp://__DNS__PEERINDEX2__.westus2.cloudapp.azure.com:8800 \
          --bind component:tcp://eth0:4004 \
          --bind network:tcp://eth0:8800 \
        \""

  rest-api:
    image: hyperledger/sawtooth-rest-api:latest
    container_name: sawtooth-rest-api-local
    ports:
      - "8008:8008"
    depends_on:
      - validator
    command: sawtooth-rest-api -v --connect tcp://validator:4004 --bind rest-api:8008
    stop_signal: SIGKILL
